select_GSE: add --pubmed option; excise-gse-by-sample: handle nnn.mmm abbreviation for GSEnnnGPLmmm

diff --git a/bin/excise-gse-by-sample b/bin/excise-gse-by-sample
--- a/bin/excise-gse-by-sample
+++ b/bin/excise-gse-by-sample
@@ -11,13 +11,14 @@
 
 args=("$@")
 
-VERSION=0.0.5
+VERSION=0.0.7
 
 # History:
 # 0.0.3: --file FILE
 # 0.0.4: --excisions EXCISIONS
 # 0.0.5: debugged
 # 0.0.6: generated name includes {TAG}{N}
+# 0.0.7: reconstruct filename from nnn.mmm format
 
 # Requires:
 #   fgrep -x
@@ -259,6 +260,23 @@ function check-sample-count {
   fi
 }
 
+# Reconstruct basename from nnn or nnn.mmm
+# i.e. return GSEnnn or GSEnnnGPLmmm
+# Example: f=$(reconstruct 123.456)
+function reconstruct {
+  local file f1 f2
+  file="$1"
+  if [[ $file =~ ^[0-9][0-9]*$ ]] ; then
+     echo GSE{$file}
+  elif [[ "$file" =~ ^[0-9][0-9]*\.[0-9][0-9]*$ ]] ; then
+     f1=${gse/[^.]*./}
+     f2=${gse/.*/}
+     echo GSE${f1}GPL{$f2}
+  else
+     echo "$file"
+  fi
+}
+
 # Syntax: excisions FILE
 # Global: DIR (a directory)
 function excisions {
@@ -271,16 +289,10 @@ function excisions {
          continue
       fi
       # Infer the actual filename:
-      if [[ $gse =~ ^[0-9][0-9]*$ ]] ; then 
-         gse="GSE$gse"
-      elif [[ $gse =~ ^[0-9][0-9]*\.[0-9][0-9]$ ]] ; then
-         g1=${gse/[^.]*./}
-         g2=${gse/.*/}
-         gse=GSE$g1.GPL$g2
-      fi
+      gse=$(reconstruct "$gse")
       if [ -r "${gse}_family.soft" ] ; then gse="${gse}_family.soft" ; fi
       if [ "$gsms" = "" ]; then
-         $COPY "${gse}" "$DIR"
+         $COPY "${gse}" "$DIR" || echo "$BN: failure: $COPY ${gse} $DIR"
          continue
       fi
       verbose "$BN: recursive call: excise-gse-by-sample --out $DIR $gse $gsms"
@@ -333,7 +345,8 @@ fi
   # Use 'sort -u' in the hope that ((NSAMPLES - XSAMPLES)) will be the correct count:
   sed -e 's/^  *//' -e 's/  *$//' -e 's/^\([0-9]\)/GSM\1/' $OMIT.bak | sort -u > $OMIT
 
-  f="$file"
+  f=reconstruct "$file"
+
   g=${f/.gz/}
   if [ "$f" = "$g" ]; then
     if [ ! -r "$f" ] ; then
